### ISSUE TITLE
starting template web.xml has old version 3.0

### ISSUE THREAD

**Issue by martin-welss** [javaee-samples/javaee7-hol#15]
the web.xml in the starting template seems to be still java ee 6:
should be version 3.1, the web.xml in the solution is correct.

<web-app version="3.0" xmlns="http://java.sun.com/xml/ns/javaee" xmlns:xsi="http://www.w3.org/200
1/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/x
ml/ns/javaee/web-app_3_0.xsd">

**Comment by arun-gupta** [comment]
Fixed and closing, thanks for reporting!
