### ISSUE TITLE
fail to run the lab with mvn wildfly:run

### ISSUE THREAD

**Issue by wangsenyuan** [javaee-samples/javaee7-hol#19]
I try to run the lab with mvn wildfly:run. it successes until step 8 (movie points). it seems wildfly doesn't run with JMS enabled. however, I googled and still don't know how to enable it with MVN. following is the exception:

org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type JMSContext with qualifiers
 @Default
  at injection point [BackedAnnotatedField] @Inject org.javaee7.movieplex7.points.ReceivePointsBean.context

**Comment by arun-gupta** [comment]
That is because by default WildFly starts in Web Profile which does not include JMS. Start it in full platform as:

```
./bin/standalone.sh -c standalone-full.xml
```

**Comment by wangsenyuan** [comment]
Thanks. 
I give up to run wildfly:run, but start it manually with standalone-full.xml; However, it still doesn't work to create the queue automatically, I have to create it in the wildfly administrative console. after that, I pass this step.

I checked the javadoc for @JMSDestinationDefinition, there should be no manually configuration for the queue. Do I understand wrong. 
- An application may use this annotation to specify a JMS {@code 
  - Destination} resource that it requires in its operational 
  - environment. This provides information that can be used at the 
  - application's deployment to provision the required resource
  - and allows an application to be deployed into a Java EE environment 
  - with more minimal administrative configuration.

So I guess it should be an implementation issue(?, it may not be a issue, but I can't find the right word). 

the wildfly I am using is wildfly-9.0.0.Final

**Comment by arun-gupta** [comment]
Here is what I did and worked:

. Start WildFly as `./wildfly-9.0.0.Final/bin/standalone.sh  -c standalone-full.xml`
. Deploy the application as `mvn wildfly:deploy -DskipTests`
. Access the application at http://localhost:8080/movieplex7

What are your steps?
