### ISSUE TITLE
Use AsciiDoc for lab instructions

### ISSUE THREAD

**Issue by arun-gupta** [javaee-samples/javaee7-hol#2]
Started the work at:

https://github.com/arun-gupta/javaee7-hol/tree/master/docs/asciidoc

**Comment by noahwhite** [comment]
@arun-gupta FWIW went to check out the link above but it looks to be stale.

**Comment by arun-gupta** [comment]
The updated docs are now at:

https://github.com/javaee-samples/javaee7-hol/tree/master/docs

**Comment by arun-gupta** [comment]
Closing an older issue
