### ISSUE TITLE
Conversion to HTML shows several warnings

### ISSUE THREAD

**Issue by arun-gupta** [javaee-samples/javaee7-hol#7]
asciidoctor: WARNING: javaee7-hol.adoc: line 132: section title out of
sequence: expected level 1, got level 2
asciidoctor: WARNING: javaee7-hol.adoc: line 268: section title out of
sequence: expected level 1, got level 2
asciidoctor: WARNING: javaee7-hol.adoc: line 389: section title out of
sequence: expected level 1, got level 2
asciidoctor: WARNING: javaee7-hol.adoc: line 4245: section title out
of sequence: expected level 1, got level 2
asciidoctor: WARNING: javaee7-hol.adoc: line 4251: list item index:
expected 2, got 1
asciidoctor: WARNING: javaee7-hol.adoc: line 4252: list item index:
expected 3, got 2
asciidoctor: WARNING: javaee7-hol.adoc: line 4253: list item index:
expected 4, got 3
asciidoctor: WARNING: javaee7-hol.adoc: line 4254: list item index:
expected 5, got 2
asciidoctor: WARNING: javaee7-hol.adoc: line 4255: list item index:
expected 6, got 3
asciidoctor: WARNING: javaee7-hol.adoc: line 4256: list item index:
expected 7, got 4
asciidoctor: WARNING: javaee7-hol.adoc: line 4257: list item index:
expected 8, got 5
asciidoctor: WARNING: javaee7-hol.adoc: line 4264: section title out
of sequence: expected level 1, got level 2
asciidoctor: WARNING: javaee7-hol.adoc: line 4270: list item index:
expected 2, got 1
asciidoctor: WARNING: javaee7-hol.adoc: line 4271: list item index:
expected 3, got 2
asciidoctor: WARNING: javaee7-hol.adoc: line 4272: list item index:
expected 4, got 3
asciidoctor: WARNING: javaee7-hol.adoc: line 4273: list item index:
expected 5, got 4
asciidoctor: WARNING: javaee7-hol.adoc: line 4275: list item index:
expected 6, got 2
asciidoctor: WARNING: javaee7-hol.adoc: line 4276: list item index:
expected 7, got 3
asciidoctor: WARNING: javaee7-hol.adoc: line 4278: list item index:
expected 8, got 4
asciidoctor: WARNING: javaee7-hol.adoc: line 4279: list item index:
expected 9, got 5
asciidoctor: WARNING: javaee7-hol.adoc: line 4290: section title out
of sequence: expected level 1, got level 2

.adoc needs cleanup.

**Comment by LightGuard** [comment]
These sort of things will be sorted out once we finish #4. We'll also need to tell asciidoctor in the main inclusion file to bump the levels of the sections when it builds it. The sections should be able to be used standalone imo.

**Comment by arun-gupta** [comment]
All these warnings are now cleaned up.
